[package]
name = "tosh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.22.1", features = ["event-stream"] }
dirs = "4.0.0"
nix = "0.23.1"
serde = "1.0.135"
#crossterm = "0.22.1"
#crosstermion = { version = "0.8.1", features = ["termion"] }
signal-hook = "0.3.13"
termion = "1.5.6"
tokio = { version = "1.15.0", features = ["full"] }
toml = "0.5.8"

[profile.release]
opt-level = "z"
lto = true
debug = false
